# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChannelConfig.ui'
#
# Created: Tue Feb 02 15:54:02 2016
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ChannelConfig(object):
    def setupUi(self, ChannelConfig):
        ChannelConfig.setObjectName(_fromUtf8("ChannelConfig"))
        ChannelConfig.resize(550, 377)
        self.gridLayout_9 = QtGui.QGridLayout(ChannelConfig)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tabWidget = QtGui.QTabWidget(ChannelConfig)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_channel_1 = QtGui.QWidget()
        self.tab_channel_1.setObjectName(_fromUtf8("tab_channel_1"))
        self.gridLayout = QtGui.QGridLayout(self.tab_channel_1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lb_ch1_model = QtGui.QLabel(self.tab_channel_1)
        self.lb_ch1_model.setObjectName(_fromUtf8("lb_ch1_model"))
        self.gridLayout.addWidget(self.lb_ch1_model, 1, 0, 1, 1)
        self.le_ch1_model = QtGui.QLineEdit(self.tab_channel_1)
        self.le_ch1_model.setEnabled(True)
        self.le_ch1_model.setMouseTracking(False)
        self.le_ch1_model.setAcceptDrops(False)
        self.le_ch1_model.setDragEnabled(False)
        self.le_ch1_model.setReadOnly(False)
        self.le_ch1_model.setObjectName(_fromUtf8("le_ch1_model"))
        self.gridLayout.addWidget(self.le_ch1_model, 1, 1, 1, 1)
        self.pte_ch1_description = QtGui.QPlainTextEdit(self.tab_channel_1)
        self.pte_ch1_description.setEnabled(True)
        self.pte_ch1_description.setObjectName(_fromUtf8("pte_ch1_description"))
        self.gridLayout.addWidget(self.pte_ch1_description, 2, 1, 1, 1)
        self.lb_ch1_description = QtGui.QLabel(self.tab_channel_1)
        self.lb_ch1_description.setObjectName(_fromUtf8("lb_ch1_description"))
        self.gridLayout.addWidget(self.lb_ch1_description, 2, 0, 1, 1)
        self.chx_channel_1 = QtGui.QCheckBox(self.tab_channel_1)
        self.chx_channel_1.setObjectName(_fromUtf8("chx_channel_1"))
        self.gridLayout.addWidget(self.chx_channel_1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_channel_1, _fromUtf8(""))
        self.tab_channel_2 = QtGui.QWidget()
        self.tab_channel_2.setObjectName(_fromUtf8("tab_channel_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_channel_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lb_ch2_description = QtGui.QLabel(self.tab_channel_2)
        self.lb_ch2_description.setObjectName(_fromUtf8("lb_ch2_description"))
        self.gridLayout_2.addWidget(self.lb_ch2_description, 2, 0, 1, 1)
        self.lb_ch2_model = QtGui.QLabel(self.tab_channel_2)
        self.lb_ch2_model.setObjectName(_fromUtf8("lb_ch2_model"))
        self.gridLayout_2.addWidget(self.lb_ch2_model, 1, 0, 1, 1)
        self.le_ch2_model = QtGui.QLineEdit(self.tab_channel_2)
        self.le_ch2_model.setMouseTracking(False)
        self.le_ch2_model.setAcceptDrops(False)
        self.le_ch2_model.setObjectName(_fromUtf8("le_ch2_model"))
        self.gridLayout_2.addWidget(self.le_ch2_model, 1, 1, 1, 1)
        self.pte_ch2_description = QtGui.QPlainTextEdit(self.tab_channel_2)
        self.pte_ch2_description.setObjectName(_fromUtf8("pte_ch2_description"))
        self.gridLayout_2.addWidget(self.pte_ch2_description, 2, 1, 1, 1)
        self.chx_channel_2 = QtGui.QCheckBox(self.tab_channel_2)
        self.chx_channel_2.setObjectName(_fromUtf8("chx_channel_2"))
        self.gridLayout_2.addWidget(self.chx_channel_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_channel_2, _fromUtf8(""))
        self.tab_channel_3 = QtGui.QWidget()
        self.tab_channel_3.setObjectName(_fromUtf8("tab_channel_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_channel_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lb_ch3_model = QtGui.QLabel(self.tab_channel_3)
        self.lb_ch3_model.setObjectName(_fromUtf8("lb_ch3_model"))
        self.gridLayout_3.addWidget(self.lb_ch3_model, 1, 0, 1, 1)
        self.lb_ch3_description = QtGui.QLabel(self.tab_channel_3)
        self.lb_ch3_description.setObjectName(_fromUtf8("lb_ch3_description"))
        self.gridLayout_3.addWidget(self.lb_ch3_description, 2, 0, 1, 1)
        self.le_ch3_model = QtGui.QLineEdit(self.tab_channel_3)
        self.le_ch3_model.setMouseTracking(False)
        self.le_ch3_model.setAcceptDrops(False)
        self.le_ch3_model.setObjectName(_fromUtf8("le_ch3_model"))
        self.gridLayout_3.addWidget(self.le_ch3_model, 1, 1, 1, 1)
        self.pte_ch3_description = QtGui.QPlainTextEdit(self.tab_channel_3)
        self.pte_ch3_description.setObjectName(_fromUtf8("pte_ch3_description"))
        self.gridLayout_3.addWidget(self.pte_ch3_description, 2, 1, 1, 1)
        self.chx_channel_3 = QtGui.QCheckBox(self.tab_channel_3)
        self.chx_channel_3.setObjectName(_fromUtf8("chx_channel_3"))
        self.gridLayout_3.addWidget(self.chx_channel_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_channel_3, _fromUtf8(""))
        self.tab_channel_4 = QtGui.QWidget()
        self.tab_channel_4.setObjectName(_fromUtf8("tab_channel_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_channel_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lb_ch4_model = QtGui.QLabel(self.tab_channel_4)
        self.lb_ch4_model.setObjectName(_fromUtf8("lb_ch4_model"))
        self.gridLayout_4.addWidget(self.lb_ch4_model, 1, 0, 1, 1)
        self.le_ch4_model = QtGui.QLineEdit(self.tab_channel_4)
        self.le_ch4_model.setMouseTracking(False)
        self.le_ch4_model.setAcceptDrops(False)
        self.le_ch4_model.setObjectName(_fromUtf8("le_ch4_model"))
        self.gridLayout_4.addWidget(self.le_ch4_model, 1, 1, 1, 1)
        self.lb_ch4_description = QtGui.QLabel(self.tab_channel_4)
        self.lb_ch4_description.setObjectName(_fromUtf8("lb_ch4_description"))
        self.gridLayout_4.addWidget(self.lb_ch4_description, 2, 0, 1, 1)
        self.pte_ch4_description = QtGui.QPlainTextEdit(self.tab_channel_4)
        self.pte_ch4_description.setObjectName(_fromUtf8("pte_ch4_description"))
        self.gridLayout_4.addWidget(self.pte_ch4_description, 2, 1, 1, 1)
        self.chx_channel_4 = QtGui.QCheckBox(self.tab_channel_4)
        self.chx_channel_4.setObjectName(_fromUtf8("chx_channel_4"))
        self.gridLayout_4.addWidget(self.chx_channel_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_channel_4, _fromUtf8(""))
        self.tab_channel_5 = QtGui.QWidget()
        self.tab_channel_5.setObjectName(_fromUtf8("tab_channel_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_channel_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pte_ch5_description = QtGui.QPlainTextEdit(self.tab_channel_5)
        self.pte_ch5_description.setObjectName(_fromUtf8("pte_ch5_description"))
        self.gridLayout_5.addWidget(self.pte_ch5_description, 2, 1, 1, 1)
        self.lb_ch5_description = QtGui.QLabel(self.tab_channel_5)
        self.lb_ch5_description.setObjectName(_fromUtf8("lb_ch5_description"))
        self.gridLayout_5.addWidget(self.lb_ch5_description, 2, 0, 1, 1)
        self.lb_ch5_model = QtGui.QLabel(self.tab_channel_5)
        self.lb_ch5_model.setObjectName(_fromUtf8("lb_ch5_model"))
        self.gridLayout_5.addWidget(self.lb_ch5_model, 1, 0, 1, 1)
        self.le_ch5_model = QtGui.QLineEdit(self.tab_channel_5)
        self.le_ch5_model.setMouseTracking(False)
        self.le_ch5_model.setAcceptDrops(False)
        self.le_ch5_model.setObjectName(_fromUtf8("le_ch5_model"))
        self.gridLayout_5.addWidget(self.le_ch5_model, 1, 1, 1, 1)
        self.chx_channel_5 = QtGui.QCheckBox(self.tab_channel_5)
        self.chx_channel_5.setObjectName(_fromUtf8("chx_channel_5"))
        self.gridLayout_5.addWidget(self.chx_channel_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_channel_5, _fromUtf8(""))
        self.tab_channel_6 = QtGui.QWidget()
        self.tab_channel_6.setObjectName(_fromUtf8("tab_channel_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_channel_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.le_ch6_model = QtGui.QLineEdit(self.tab_channel_6)
        self.le_ch6_model.setMouseTracking(False)
        self.le_ch6_model.setAcceptDrops(False)
        self.le_ch6_model.setObjectName(_fromUtf8("le_ch6_model"))
        self.gridLayout_6.addWidget(self.le_ch6_model, 1, 1, 1, 1)
        self.lb_ch6_description = QtGui.QLabel(self.tab_channel_6)
        self.lb_ch6_description.setObjectName(_fromUtf8("lb_ch6_description"))
        self.gridLayout_6.addWidget(self.lb_ch6_description, 2, 0, 1, 1)
        self.lb_ch6_model = QtGui.QLabel(self.tab_channel_6)
        self.lb_ch6_model.setObjectName(_fromUtf8("lb_ch6_model"))
        self.gridLayout_6.addWidget(self.lb_ch6_model, 1, 0, 1, 1)
        self.pte_ch6_description = QtGui.QPlainTextEdit(self.tab_channel_6)
        self.pte_ch6_description.setObjectName(_fromUtf8("pte_ch6_description"))
        self.gridLayout_6.addWidget(self.pte_ch6_description, 2, 1, 1, 1)
        self.chx_channel_6 = QtGui.QCheckBox(self.tab_channel_6)
        self.chx_channel_6.setObjectName(_fromUtf8("chx_channel_6"))
        self.gridLayout_6.addWidget(self.chx_channel_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_channel_6, _fromUtf8(""))
        self.tab_channel_7 = QtGui.QWidget()
        self.tab_channel_7.setObjectName(_fromUtf8("tab_channel_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_channel_7)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lb_ch7_description = QtGui.QLabel(self.tab_channel_7)
        self.lb_ch7_description.setObjectName(_fromUtf8("lb_ch7_description"))
        self.gridLayout_7.addWidget(self.lb_ch7_description, 2, 0, 1, 1)
        self.le_ch7_model = QtGui.QLineEdit(self.tab_channel_7)
        self.le_ch7_model.setMouseTracking(False)
        self.le_ch7_model.setAcceptDrops(False)
        self.le_ch7_model.setObjectName(_fromUtf8("le_ch7_model"))
        self.gridLayout_7.addWidget(self.le_ch7_model, 1, 1, 1, 1)
        self.lb_ch7_model = QtGui.QLabel(self.tab_channel_7)
        self.lb_ch7_model.setObjectName(_fromUtf8("lb_ch7_model"))
        self.gridLayout_7.addWidget(self.lb_ch7_model, 1, 0, 1, 1)
        self.pte_ch7_description = QtGui.QPlainTextEdit(self.tab_channel_7)
        self.pte_ch7_description.setObjectName(_fromUtf8("pte_ch7_description"))
        self.gridLayout_7.addWidget(self.pte_ch7_description, 2, 1, 1, 1)
        self.chx_channel_7 = QtGui.QCheckBox(self.tab_channel_7)
        self.chx_channel_7.setObjectName(_fromUtf8("chx_channel_7"))
        self.gridLayout_7.addWidget(self.chx_channel_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_channel_7, _fromUtf8(""))
        self.tab_channel_8 = QtGui.QWidget()
        self.tab_channel_8.setObjectName(_fromUtf8("tab_channel_8"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_channel_8)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lb_ch8_model = QtGui.QLabel(self.tab_channel_8)
        self.lb_ch8_model.setObjectName(_fromUtf8("lb_ch8_model"))
        self.gridLayout_8.addWidget(self.lb_ch8_model, 1, 0, 1, 1)
        self.pte_ch8_description = QtGui.QPlainTextEdit(self.tab_channel_8)
        self.pte_ch8_description.setObjectName(_fromUtf8("pte_ch8_description"))
        self.gridLayout_8.addWidget(self.pte_ch8_description, 2, 1, 1, 1)
        self.lb_ch8_description = QtGui.QLabel(self.tab_channel_8)
        self.lb_ch8_description.setObjectName(_fromUtf8("lb_ch8_description"))
        self.gridLayout_8.addWidget(self.lb_ch8_description, 2, 0, 1, 1)
        self.le_ch8_model = QtGui.QLineEdit(self.tab_channel_8)
        self.le_ch8_model.setMouseTracking(False)
        self.le_ch8_model.setAcceptDrops(False)
        self.le_ch8_model.setObjectName(_fromUtf8("le_ch8_model"))
        self.gridLayout_8.addWidget(self.le_ch8_model, 1, 1, 1, 1)
        self.chx_channel_8 = QtGui.QCheckBox(self.tab_channel_8)
        self.chx_channel_8.setObjectName(_fromUtf8("chx_channel_8"))
        self.gridLayout_8.addWidget(self.chx_channel_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_channel_8, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.tabWidget, 0, 1, 1, 3)
        self.pb_accept = QtGui.QPushButton(ChannelConfig)
        self.pb_accept.setObjectName(_fromUtf8("pb_accept"))
        self.gridLayout_9.addWidget(self.pb_accept, 1, 2, 1, 1)
        self.pb_cancel = QtGui.QPushButton(ChannelConfig)
        self.pb_cancel.setObjectName(_fromUtf8("pb_cancel"))
        self.gridLayout_9.addWidget(self.pb_cancel, 1, 3, 1, 1)

        self.retranslateUi(ChannelConfig)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ChannelConfig)

    def retranslateUi(self, ChannelConfig):
        ChannelConfig.setWindowTitle(QtGui.QApplication.translate("ChannelConfig", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch1_model.setText(QtGui.QApplication.translate("ChannelConfig", "Nro de Modelo del Dispositivo", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch1_description.setText(QtGui.QApplication.translate("ChannelConfig", "Descripción", None, QtGui.QApplication.UnicodeUTF8))
        self.chx_channel_1.setText(QtGui.QApplication.translate("ChannelConfig", "Habilitado", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_channel_1), QtGui.QApplication.translate("ChannelConfig", "Canal 1", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch2_description.setText(QtGui.QApplication.translate("ChannelConfig", "Descripción", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch2_model.setText(QtGui.QApplication.translate("ChannelConfig", "Nro de Modelo del Dispositivo", None, QtGui.QApplication.UnicodeUTF8))
        self.chx_channel_2.setText(QtGui.QApplication.translate("ChannelConfig", "Habilitado", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_channel_2), QtGui.QApplication.translate("ChannelConfig", "Canal 2", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch3_model.setText(QtGui.QApplication.translate("ChannelConfig", "Nro de Modelo del Dispositivo", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch3_description.setText(QtGui.QApplication.translate("ChannelConfig", "Descripción", None, QtGui.QApplication.UnicodeUTF8))
        self.chx_channel_3.setText(QtGui.QApplication.translate("ChannelConfig", "Habilitado", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_channel_3), QtGui.QApplication.translate("ChannelConfig", "Canal 3", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch4_model.setText(QtGui.QApplication.translate("ChannelConfig", "Nro de Modelo del Dispositivo", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch4_description.setText(QtGui.QApplication.translate("ChannelConfig", "Descripción", None, QtGui.QApplication.UnicodeUTF8))
        self.chx_channel_4.setText(QtGui.QApplication.translate("ChannelConfig", "Habilitado", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_channel_4), QtGui.QApplication.translate("ChannelConfig", "Canal 4", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch5_description.setText(QtGui.QApplication.translate("ChannelConfig", "Descripción", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch5_model.setText(QtGui.QApplication.translate("ChannelConfig", "Nro de Modelo del Dispositivo", None, QtGui.QApplication.UnicodeUTF8))
        self.chx_channel_5.setText(QtGui.QApplication.translate("ChannelConfig", "Habilitado", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_channel_5), QtGui.QApplication.translate("ChannelConfig", "Canal 5", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch6_description.setText(QtGui.QApplication.translate("ChannelConfig", "Descripción", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch6_model.setText(QtGui.QApplication.translate("ChannelConfig", "Nro de Modelo del Dispositivo", None, QtGui.QApplication.UnicodeUTF8))
        self.chx_channel_6.setText(QtGui.QApplication.translate("ChannelConfig", "Habilitado", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_channel_6), QtGui.QApplication.translate("ChannelConfig", "Canal 6", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch7_description.setText(QtGui.QApplication.translate("ChannelConfig", "Descripción", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch7_model.setText(QtGui.QApplication.translate("ChannelConfig", "Nro de Modelo del Dispositivo", None, QtGui.QApplication.UnicodeUTF8))
        self.chx_channel_7.setText(QtGui.QApplication.translate("ChannelConfig", "Habilitado", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_channel_7), QtGui.QApplication.translate("ChannelConfig", "Canal 7", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch8_model.setText(QtGui.QApplication.translate("ChannelConfig", "Nro de Modelo del Dispositivo", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ch8_description.setText(QtGui.QApplication.translate("ChannelConfig", "Descripción", None, QtGui.QApplication.UnicodeUTF8))
        self.chx_channel_8.setText(QtGui.QApplication.translate("ChannelConfig", "Habilitado", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_channel_8), QtGui.QApplication.translate("ChannelConfig", "Canal 8", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_accept.setText(QtGui.QApplication.translate("ChannelConfig", "Aceptar", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("ChannelConfig", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))

