# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Tue Sep 11 11:52:57 2012
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(871, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.mainTabs = QtGui.QTabWidget(self.centralwidget)
        self.mainTabs.setObjectName(_fromUtf8("mainTabs"))
        self.settings = QtGui.QWidget()
        self.settings.setObjectName(_fromUtf8("settings"))
        self.gridLayout_13 = QtGui.QGridLayout(self.settings)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gb_datafile = QtGui.QGroupBox(self.settings)
        self.gb_datafile.setMaximumSize(QtCore.QSize(829, 265))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gb_datafile.setFont(font)
        self.gb_datafile.setObjectName(_fromUtf8("gb_datafile"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gb_datafile)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lb_file = QtGui.QLabel(self.gb_datafile)
        self.lb_file.setObjectName(_fromUtf8("lb_file"))
        self.gridLayout_2.addWidget(self.lb_file, 0, 0, 1, 1)
        self.le_file = QtGui.QLineEdit(self.gb_datafile)
        self.le_file.setObjectName(_fromUtf8("le_file"))
        self.gridLayout_2.addWidget(self.le_file, 0, 1, 1, 1)
        self.tlb_open = QtGui.QToolButton(self.gb_datafile)
        self.tlb_open.setObjectName(_fromUtf8("tlb_open"))
        self.gridLayout_2.addWidget(self.tlb_open, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.gb_datafile)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.le_user = QtGui.QLineEdit(self.gb_datafile)
        self.le_user.setObjectName(_fromUtf8("le_user"))
        self.gridLayout_2.addWidget(self.le_user, 1, 1, 1, 2)
        self.label_9 = QtGui.QLabel(self.gb_datafile)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.le_material = QtGui.QLineEdit(self.gb_datafile)
        self.le_material.setObjectName(_fromUtf8("le_material"))
        self.gridLayout_2.addWidget(self.le_material, 2, 1, 1, 2)
        self.lb_header = QtGui.QLabel(self.gb_datafile)
        self.lb_header.setObjectName(_fromUtf8("lb_header"))
        self.gridLayout_2.addWidget(self.lb_header, 3, 0, 1, 1)
        self.te_header = QtGui.QTextEdit(self.gb_datafile)
        self.te_header.setObjectName(_fromUtf8("te_header"))
        self.gridLayout_2.addWidget(self.te_header, 4, 0, 1, 3)
        self.gridLayout_13.addWidget(self.gb_datafile, 0, 0, 1, 2)
        self.gb_settings = QtGui.QGroupBox(self.settings)
        self.gb_settings.setMaximumSize(QtCore.QSize(412, 226))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gb_settings.setFont(font)
        self.gb_settings.setObjectName(_fromUtf8("gb_settings"))
        self.gridLayout = QtGui.QGridLayout(self.gb_settings)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.gb_settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.cb_port = QtGui.QComboBox(self.gb_settings)
        self.cb_port.setObjectName(_fromUtf8("cb_port"))
        self.gridLayout.addWidget(self.cb_port, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gb_settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.cb_baudrate = QtGui.QComboBox(self.gb_settings)
        self.cb_baudrate.setObjectName(_fromUtf8("cb_baudrate"))
        self.cb_baudrate.addItem(_fromUtf8(""))
        self.cb_baudrate.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cb_baudrate, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gb_settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.cb_databits = QtGui.QComboBox(self.gb_settings)
        self.cb_databits.setEnabled(False)
        self.cb_databits.setObjectName(_fromUtf8("cb_databits"))
        self.cb_databits.addItem(_fromUtf8(""))
        self.cb_databits.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cb_databits, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gb_settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.cb_stopbits = QtGui.QComboBox(self.gb_settings)
        self.cb_stopbits.setEnabled(False)
        self.cb_stopbits.setObjectName(_fromUtf8("cb_stopbits"))
        self.cb_stopbits.addItem(_fromUtf8(""))
        self.cb_stopbits.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cb_stopbits, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gb_settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.cd_parity = QtGui.QComboBox(self.gb_settings)
        self.cd_parity.setEnabled(False)
        self.cd_parity.setObjectName(_fromUtf8("cd_parity"))
        self.cd_parity.addItem(_fromUtf8(""))
        self.cd_parity.addItem(_fromUtf8(""))
        self.cd_parity.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cd_parity, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.gb_settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.cb_handshake = QtGui.QComboBox(self.gb_settings)
        self.cb_handshake.setEnabled(False)
        self.cb_handshake.setObjectName(_fromUtf8("cb_handshake"))
        self.cb_handshake.addItem(_fromUtf8(""))
        self.cb_handshake.addItem(_fromUtf8(""))
        self.cb_handshake.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cb_handshake, 5, 1, 1, 1)
        self.lb_interv = QtGui.QLabel(self.gb_settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_interv.setFont(font)
        self.lb_interv.setObjectName(_fromUtf8("lb_interv"))
        self.gridLayout.addWidget(self.lb_interv, 6, 0, 1, 1)
        self.dsb_step = QtGui.QDoubleSpinBox(self.gb_settings)
        self.dsb_step.setObjectName(_fromUtf8("dsb_step"))
        self.gridLayout.addWidget(self.dsb_step, 6, 1, 1, 1)
        self.gridLayout_13.addWidget(self.gb_settings, 1, 0, 2, 1)
        self.cb_start = QtGui.QCommandLinkButton(self.settings)
        self.cb_start.setMaximumSize(QtCore.QSize(411, 110))
        self.cb_start.setObjectName(_fromUtf8("cb_start"))
        self.gridLayout_13.addWidget(self.cb_start, 1, 1, 1, 1)
        self.cb_end = QtGui.QCommandLinkButton(self.settings)
        self.cb_end.setMaximumSize(QtCore.QSize(411, 110))
        self.cb_end.setObjectName(_fromUtf8("cb_end"))
        self.gridLayout_13.addWidget(self.cb_end, 2, 1, 1, 1)
        self.mainTabs.addTab(self.settings, _fromUtf8(""))
        self.ploter = QtGui.QWidget()
        self.ploter.setObjectName(_fromUtf8("ploter"))
        self.gridLayout_12 = QtGui.QGridLayout(self.ploter)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gb_auxplots = QtGui.QGroupBox(self.ploter)
        self.gb_auxplots.setMaximumSize(QtCore.QSize(361, 16777215))
        self.gb_auxplots.setObjectName(_fromUtf8("gb_auxplots"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gb_auxplots)
        self.gridLayout_7.setMargin(3)
        self.gridLayout_7.setHorizontalSpacing(3)
        self.gridLayout_7.setVerticalSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gb_aux1_plt = QtGui.QGroupBox(self.gb_auxplots)
        self.gb_aux1_plt.setObjectName(_fromUtf8("gb_aux1_plt"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gb_aux1_plt)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.aux1_plot = QtGui.QWidget(self.gb_aux1_plt)
        self.aux1_plot.setObjectName(_fromUtf8("aux1_plot"))
        self.verticalLayout.addWidget(self.aux1_plot)
        self.gridLayout_7.addWidget(self.gb_aux1_plt, 0, 0, 1, 1)
        self.gb_aux2_plt = QtGui.QGroupBox(self.gb_auxplots)
        self.gb_aux2_plt.setObjectName(_fromUtf8("gb_aux2_plt"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gb_aux2_plt)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.aux2_plot = QtGui.QWidget(self.gb_aux2_plt)
        self.aux2_plot.setObjectName(_fromUtf8("aux2_plot"))
        self.gridLayout_5.addWidget(self.aux2_plot, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.gb_aux2_plt, 1, 0, 1, 1)
        self.gb_aux3_plt = QtGui.QGroupBox(self.gb_auxplots)
        self.gb_aux3_plt.setObjectName(_fromUtf8("gb_aux3_plt"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gb_aux3_plt)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.aux3_plot = QtGui.QWidget(self.gb_aux3_plt)
        self.aux3_plot.setObjectName(_fromUtf8("aux3_plot"))
        self.gridLayout_4.addWidget(self.aux3_plot, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.gb_aux3_plt, 2, 0, 1, 1)
        self.gridLayout_12.addWidget(self.gb_auxplots, 0, 0, 2, 1)
        self.gb_main_plt = QtGui.QGroupBox(self.ploter)
        self.gb_main_plt.setObjectName(_fromUtf8("gb_main_plt"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gb_main_plt)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.main_plot = QtGui.QWidget(self.gb_main_plt)
        self.main_plot.setObjectName(_fromUtf8("main_plot"))
        self.gridLayout_6.addWidget(self.main_plot, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.gb_main_plt, 1, 1, 1, 1)
        self.gb_display = QtGui.QGroupBox(self.ploter)
        self.gb_display.setMaximumSize(QtCore.QSize(16777215, 91))
        self.gb_display.setObjectName(_fromUtf8("gb_display"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gb_display)
        self.gridLayout_11.setContentsMargins(9, 0, 9, 9)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.gb_time_display = QtGui.QGroupBox(self.gb_display)
        self.gb_time_display.setObjectName(_fromUtf8("gb_time_display"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gb_time_display)
        self.gridLayout_8.setContentsMargins(3, 0, 3, 3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lcd_time_hour = QtGui.QLCDNumber(self.gb_time_display)
        self.lcd_time_hour.setDigitCount(2)
        self.lcd_time_hour.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_time_hour.setProperty(_fromUtf8("intValue"), 0)
        self.lcd_time_hour.setObjectName(_fromUtf8("lcd_time_hour"))
        self.gridLayout_8.addWidget(self.lcd_time_hour, 0, 0, 1, 1)
        self.lcd_time_min = QtGui.QLCDNumber(self.gb_time_display)
        self.lcd_time_min.setDigitCount(2)
        self.lcd_time_min.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_time_min.setProperty(_fromUtf8("intValue"), 0)
        self.lcd_time_min.setObjectName(_fromUtf8("lcd_time_min"))
        self.gridLayout_8.addWidget(self.lcd_time_min, 0, 1, 1, 1)
        self.lcd_time_seg = QtGui.QLCDNumber(self.gb_time_display)
        self.lcd_time_seg.setDigitCount(2)
        self.lcd_time_seg.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_time_seg.setProperty(_fromUtf8("intValue"), 0)
        self.lcd_time_seg.setObjectName(_fromUtf8("lcd_time_seg"))
        self.gridLayout_8.addWidget(self.lcd_time_seg, 0, 2, 1, 1)
        self.gridLayout_11.addWidget(self.gb_time_display, 0, 0, 1, 1)
        self.gb_temp_display = QtGui.QGroupBox(self.gb_display)
        self.gb_temp_display.setObjectName(_fromUtf8("gb_temp_display"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gb_temp_display)
        self.gridLayout_9.setContentsMargins(3, 0, 3, 3)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lcd_temp = QtGui.QLCDNumber(self.gb_temp_display)
        self.lcd_temp.setObjectName(_fromUtf8("lcd_temp"))
        self.gridLayout_9.addWidget(self.lcd_temp, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.gb_temp_display, 0, 1, 1, 1)
        self.gb_lvdt_display = QtGui.QGroupBox(self.gb_display)
        self.gb_lvdt_display.setObjectName(_fromUtf8("gb_lvdt_display"))
        self.gridLayout_10 = QtGui.QGridLayout(self.gb_lvdt_display)
        self.gridLayout_10.setContentsMargins(3, 0, 3, 3)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.lcd_lvdt = QtGui.QLCDNumber(self.gb_lvdt_display)
        self.lcd_lvdt.setObjectName(_fromUtf8("lcd_lvdt"))
        self.gridLayout_10.addWidget(self.lcd_lvdt, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.gb_lvdt_display, 0, 2, 1, 1)
        self.gridLayout_12.addWidget(self.gb_display, 0, 1, 1, 1)
        self.mainTabs.addTab(self.ploter, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.mainTabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 871, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuQuit = QtGui.QMenu(self.menubar)
        self.menuQuit.setObjectName(_fromUtf8("menuQuit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuQuit.addAction(self.actionQuit)
        self.menubar.addAction(self.menuQuit.menuAction())

        self.retranslateUi(MainWindow)
        self.mainTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_datafile.setTitle(QtGui.QApplication.translate("MainWindow", "Almacenamiento de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_file.setText(QtGui.QApplication.translate("MainWindow", "Archivo de destino", None, QtGui.QApplication.UnicodeUTF8))
        self.tlb_open.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Operador", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Material a ensayar", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_header.setText(QtGui.QApplication.translate("MainWindow", "Observaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_settings.setTitle(QtGui.QApplication.translate("MainWindow", "Comunicacion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Puerto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Baudios", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_baudrate.setItemText(0, QtGui.QApplication.translate("MainWindow", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_baudrate.setItemText(1, QtGui.QApplication.translate("MainWindow", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Bit de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_databits.setItemText(0, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_databits.setItemText(1, QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Bits de parada", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_stopbits.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_stopbits.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Paridad", None, QtGui.QApplication.UnicodeUTF8))
        self.cd_parity.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.cd_parity.setItemText(1, QtGui.QApplication.translate("MainWindow", "Odd", None, QtGui.QApplication.UnicodeUTF8))
        self.cd_parity.setItemText(2, QtGui.QApplication.translate("MainWindow", "Even", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Control de Flujo", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_handshake.setItemText(0, QtGui.QApplication.translate("MainWindow", "NONE", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_handshake.setItemText(1, QtGui.QApplication.translate("MainWindow", "XON/XOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_handshake.setItemText(2, QtGui.QApplication.translate("MainWindow", "CTS/CTR", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_interv.setText(QtGui.QApplication.translate("MainWindow", "Intervalo de lectura (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_start.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_end.setText(QtGui.QApplication.translate("MainWindow", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.settings), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_auxplots.setTitle(QtGui.QApplication.translate("MainWindow", "Auxiliares", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_aux1_plt.setTitle(QtGui.QApplication.translate("MainWindow", "Auxiliar 1", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_aux2_plt.setTitle(QtGui.QApplication.translate("MainWindow", "Auxiliar 2", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_aux3_plt.setTitle(QtGui.QApplication.translate("MainWindow", "Auxiliar 3", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_main_plt.setTitle(QtGui.QApplication.translate("MainWindow", "Principal", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_display.setTitle(QtGui.QApplication.translate("MainWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_time_display.setTitle(QtGui.QApplication.translate("MainWindow", "Tiempo Transcurrido", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_temp_display.setTitle(QtGui.QApplication.translate("MainWindow", "Temperatura", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_lvdt_display.setTitle(QtGui.QApplication.translate("MainWindow", "Deformacion", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.ploter), QtGui.QApplication.translate("MainWindow", "Ploter", None, QtGui.QApplication.UnicodeUTF8))
        self.menuQuit.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))

